### ISSUE TITLE
TikTok run on Android emulator

### ISSUE THREAD

**Issue by okcatman** [instabotai/tiktokbot#1]
hello，i test tiktok app on Android emulator like mumu emulator and others , because tiktok will check device type and platform. i see you run tiktok on bluestacks rmulator succeccfully.it's fun,
i wanna know if the bluestacks can Shielding Tiktok detection？it's will be very useful ! Thank you.

**Comment by steffanjensen** [comment]
No it's still detected. Actions are just limited.

**Comment by tmxd09887** [comment]
hello,I cant run tiktok on nox emulator.

Do you test the bot with a real phone?
